"""Add image_url to Book and Temple models

Revision ID: 682c897b2220
Revises: b51a5014e405
Create Date: 2025-10-19 11:39:35.389131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682c897b2220'
down_revision = 'b51a5014e405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
